---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app2
  labels:
    app: hello-app2
    name: hello-app2
  namespace: compreview-install
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-app2
      name: hello-app2
  template:
    metadata:
      labels:
        app: hello-app2
        name: hello-app2
    spec:
      containers:
      - name: hello-app2
        image: central-quay-registry.apps.ocp4.example.com/cloudadmin/hello-app:v11
      imagePullSecrets: 
      - name: cloudadmin-pullrobot-pull-secret
---
